# CREATE
POST http://localhost:3000/product/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE1NTY1ODI1NDd9.uq88w82YKnNlnQ2UXEvQxKdK7oFxFhRVcJ4PkhmhQug
Content-Type: application/json

{
  "name": "Node js",
  "reference": "JFSSA56D22S",
  "category": "5cc8dc3b1c9d4400000c4ff8"
}

###{
#  "name": "Polo USNN",
#  "reference": "JISA5420T",
#  "category": "5cc8dc3b1c9d4400000c4ff8"
}

###
# DELETE
DELETE http://localhost:3000/product/delete/5ccdced103abd72e18eec080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE1NTY1ODI1NDd9.uq88w82YKnNlnQ2UXEvQxKdK7oFxFhRVcJ4PkhmhQug

###

###

# UPDATE
PUT http://localhost:3000/product/update/5ccdced103abd72e18eec080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE1NTY1ODI1NDd9.uq88w82YKnNlnQ2UXEvQxKdK7oFxFhRVcJ4PkhmhQug
Content-Type: application/json

{
  "dataForUpdate": [
    {
      "key": "name",
      "value": "Other Product"
    },
    {
      "key": "reference",
      "value": "AI165SASN"
    }
  ]
}

#### GET ONE
GET http://localhost:3000/product/one/5ccb33706995c4ee6ad5ba68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE1NTY1ODI1NDd9.uq88w82YKnNlnQ2UXEvQxKdK7oFxFhRVcJ4PkhmhQug

###

#### GET ALL
GET http://localhost:3000/product/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE1NTY1ODI1NDd9.uq88w82YKnNlnQ2UXEvQxKdK7oFxFhRVcJ4PkhmhQug

###
